# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-20 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='destination',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
