# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-20 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180419_2229'),
        ('destinations', '0002_auto_20180420_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='users.User'),
            preserve_default=False,
        ),
    ]
